-- Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_code TEXT NOT NULL, -- Target user code (e.g., ADM-000, WRK-123)
    type TEXT NOT NULL CHECK (type IN ('success', 'warning', 'info', 'error', 'validation')),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for faster queries by user
CREATE INDEX IF NOT EXISTS idx_notifications_user_code ON notifications(user_code);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);

-- Row Level Security
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own notifications
-- Note: This requires the 'user_code' in the auth.jwt() or a lookup.
-- For simple demo/hybrid with 'anon' key, we might allow public read/write if we trust the client logic,
-- OR better: Allow Authenticated users to see rows where user_code matches their profile.
-- Since user_code isn't standard Supabase Auth ID, we'll keep it simple for this migration:

-- Allow all access for now to ensure the demo features work without complex auth setup
CREATE POLICY "Allow all access to notifications"
ON notifications FOR ALL
USING (true)
WITH CHECK (true);
