-- Create notification_preferences table
-- Stores per-user notification preferences scoped to a salon
CREATE TABLE IF NOT EXISTS notification_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id INTEGER NOT NULL,
    user_code TEXT NOT NULL,
    -- Channel preferences stored as JSONB array
    -- Each element: { "id": "revenue", "email": true, "push": true, "sms": false }
    channel_preferences JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- Email digest frequency: off, daily, weekly, monthly
    digest_frequency TEXT NOT NULL DEFAULT 'daily' CHECK (digest_frequency IN ('off', 'daily', 'weekly', 'monthly')),
    -- Quiet hours
    quiet_hours_enabled BOOLEAN NOT NULL DEFAULT false,
    quiet_hours_start TEXT DEFAULT '22:00',
    quiet_hours_end TEXT DEFAULT '08:00',
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    -- Unique constraint: one preference record per user per salon
    UNIQUE (salon_id, user_code)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_notification_prefs_salon ON notification_preferences(salon_id);
CREATE INDEX IF NOT EXISTS idx_notification_prefs_user ON notification_preferences(user_code);

-- Row Level Security
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;

-- Allow all access (same pattern as notifications table for demo/hybrid mode)
CREATE POLICY "Allow all access to notification_preferences"
ON notification_preferences FOR ALL
USING (true)
WITH CHECK (true);

-- Auto-update updated_at on row change
CREATE OR REPLACE FUNCTION update_notification_preferences_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER trigger_update_notification_preferences_updated_at
    BEFORE UPDATE ON notification_preferences
    FOR EACH ROW
    EXECUTE FUNCTION update_notification_preferences_updated_at();
